### ISSUE TITLE
Crash by Rifted Enderman in Latest Version

### ISSUE THREAD

**Issue by CCCClear** [Un-Original1/BeastSlayer#10]
Time: 5/10/22 9:14 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.EntityLivingBase.func_70685_l(EntityLivingBase.java:2526)
	at com.unoriginal.ancientbeasts.entity.Entities.EntityRiftedEnderman.func_70636_d(EntityRiftedEnderman.java:250)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.EntityLivingBase.func_70685_l(EntityLivingBase.java:2526)
	at com.unoriginal.ancientbeasts.entity.Entities.EntityRiftedEnderman.func_70636_d(EntityRiftedEnderman.java:250)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: ancientbeasts:rifted_enderman (com.unoriginal.ancientbeasts.entity.Entities.EntityRiftedEnderman)
	Entity ID: 4310
	Entity Name: Rifted Enderman
	Entity's Exact location: 24.70, 75.00, 279.08
	Entity's Block location: World: (24,75,279), Chunk: (at 8,4,7 in 1,17; contains blocks 16,0,272 to 31,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

**Comment by Un-Original1** [comment]
I uploaded a fix, if you can confirm that this issue is fixed I'll be closing this issue.

**Comment by CCCClear** [comment]
I just had time to test it.
In the last version, this bug happened when I switched from Survival mode to Creative mode and then to survival mode, the rifted enderman lost its hatred of me and the game crashed.
After the fix, the same action will cause the end of rifted enderman to lose its hatred for me, but the game will not crash. 
I think the ticking entity issue has been fixed, you can turn it off now.
